apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    environment-id: env_72f0195f-1408-42ed-aadc-eea1c1c60b01
    project-id: project_09675c76-2922-4e5e-ba89-7050a7895743
    project-name: dogHouse04354
    environment-name: dev
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
